name: Ubuntu SSH

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  tmate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        
      - name: Install deps
        run: |
          sudo apt update && sudo apt install tmate -y

      - name: Generate Tmate Session
        run: |
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt

      - name: Blank Output
        run: |
          bash blank.sh
